DROP TABLE if EXISTS test.INVENTORY_LOG;
GO

DROP TABLE if EXISTS test.INVENTORY;
GO

CREATE TABLE test.INVENTORY (ITEM VARCHAR(20) primary key , QUANTITY INT);
GO

CREATE TABLE test.INVENTORY_LOG (
  ITEM     VARCHAR(20),
  QUANTITY INT,
  REGDATE  DATE);
go

INSERT INTO test.INVENTORY VALUES ('Notebook', 10);
go
